name: e2e

on:
  push:
    branches: [ e2e-local ]
  pull_request:
    branches: [ e2e-local ]
env:
  REGISTRY: ${{ secrets.REGISTRY}}
  go_version: '1.16.0'
  golangci_version: '1.37.0'
jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: clone operator
      run: |
        cd ../
        git clone https://github.com/kir0108/csi-baremetal.git
        git clone https://github.com/dell/csi-baremetal-operator.git 

    - name: Set environment variables
      run: |
        echo "CSI_BAREMETAL_DIR=$RUNNER_WORKSPACE/csi-baremetal/" >> $GITHUB_ENV
        echo "CSI_BAREMETAL_OPERATOR_DIR=$RUNNER_WORKSPACE/csi-baremetal-operator/" >> $GITHUB_ENV

    - name: Update apt
      run: sudo apt update

    - name: install lvm
      run: sudo apt-get install -y lvm2

    - name: install unzip
      run: sudo apt install unzip

    - name: install gcc
      run: sudo apt -y install build-essential

    - name: Prepare Golang 
      uses: actions/setup-go@v2
      with:
        go-version: ${{env.go_version}}

    - name: Install helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: kind install
      run: |
        wget -O kind https://github.com/painhardcore/builder/releases/download/0.0.1-alpha/kind_v0.8.1
        sudo chmod +x kind
        sudo mv kind /usr/bin
          
    - name: kubectl install
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client 
   
    - name: add CSI_VERSION
      run: |
        cd ${{env.CSI_BAREMETAL_DIR}}
        echo "CSI_VERSION=`make version`" >> $GITHUB_ENV
   
    - name: Get dependencies
      run: make dependency

    - name: Compile proto files
      run: |
        sudo apt install protobuf-compiler
        sudo apt install golang-goprotobuf-dev
        make install-compile-proto

    - name: Generate CRD
      run: |
        make install-controller-gen 
        make generate-deepcopy

    - name: Build binary
      run: |
        make build
        make DRIVE_MANAGER_TYPE=loopbackmgr build-drivemgr

    - name: Download health-probe
      run: make download-grpc-health-probe

    - name: Build docker images
      run: |
        make images REGISTRY=${{ env.REGISTRY }}
        make DRIVE_MANAGER_TYPE=loopbackmgr image-drivemgr REGISTRY=${{ env.REGISTRY }}
    
    - name: docker-build operators 
      run: |
        cd ${{env.CSI_BAREMETAL_OPERATOR_DIR}}
        echo "CSI_OPERATOR_VERSION=`make version`" >> $GITHUB_ENV
        make docker-build REGISTRY=${{ env.REGISTRY }}

    - name: Kind preparation
      run: |
        cd ${{env.CSI_BAREMETAL_DIR}}
        make kind-build
        make kind-create-cluster
        kubectl cluster-info --context kind-kind
        kubectl get pods -o wide --all-namespaces 
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
      
    - name: wait
      uses: jakejarvis/wait-action@master
      with:
        time: '60s' 

    - name: Check pods
      run: |
        kubectl cluster-info --context kind-kind
        kubectl get pods -o wide --all-namespaces
 
    - name: Sidecars preparing
      run: |
        make deps-docker-pull
        make deps-docker-tag

    - name: Retag CSI images and load them to kind
      run: |
        docker images 
        make kind-tag-images TAG=$CSI_VERSION REGISTRY=${{ env.REGISTRY }}
        make kind-load-images TAG=$CSI_VERSION REGISTRY=${{ env.REGISTRY }}
        make load-operator-image OPERATOR_VERSION=$CSI_OPERATOR_VERSION REGISTRY=${{ env.REGISTRY }}
          
    - name: Make test
      run: make test-ci CSI_VERSION=$CSI_VERSION OPERATOR_VERSION=$CSI_OPERATOR_VERSION CHARTS_DIR=${{env.CSI_BAREMETAL_OPERATOR_DIR}}charts
